version: '3.7'

services:

  mysql:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_DATABASE=payment
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  payment:
    build: .
    restart: always
    ports:
      - 5001:5001
    links:
    - db

    
